### ISSUE TITLE
how to run apache services used the cirros ?

### ISSUE THREAD

**Issue by lioncui** [csabahenk/cirros#13]
i want to run apache services by cirros , beacuse it's a very small  operation system.

**Comment by csabahenk** [comment]
Hi, first of all, this is not the main [CirrOS](https://launchpad.net/cirros) project but a special purpose fork of it. Second, it's not under active development at the moment.

Apache is not contained in the standard CirrOS image. However, there is no intrinsic limit to extend CirrOS. (That implies building a custom CirrOS image, as post-build modifications are not supported.) You can build a custom CirrOS image with whatever software you would like to have in it; of course if you put big things into it, then it won't be a _very small operating system_ any more. There is just one requirement: CirrOS is built against [µClibc](http://www.uclibc.org/), so the software you build for CirrOS should be possible to build against µClibc too.

With respect to Apache: CirrOS is built with [Buildroot](http://buildroot.uclibc.org/) and Buildroot does have an [Apache package](http://git.buildroot.net/buildroot/tree/package/apache). So the final answer to your question depends on what services you want to run and what additional bits are needed for those.
