### ISSUE TITLE
Enabled nfsv4 requires libnfsidmap package that is absent in buildroot

### ISSUE THREAD

**Issue by vponomaryov** [csabahenk/cirros#2]
Patch "nfs-utils-enable-nfsv4.patch" enables nfsv4, but nfsv4 requires package libnfsidmap in buildroot.
If we use this patch, we get error with absent dependent package while building buildroot for a given arch.

**Comment by csabahenk** [comment]
Yes, I know of the issue, I have a fix being tested.
